#!/usr/bin/env python3
"""Machine verification of theory-track report #6 (archive/pro_report_6.md), 2026-07-26.

Sections:
  A. Multiplier-addition theorem: hypothesis table (integer side ratios + exact corner-angle
     match + fundamental-cell split) for all six Group-2 rows and Group-1 shapes 4/5;
     non-integrality of both assignments on the gamma=2alpha branch (no unconditional closure).
  B. Decomposition partition: (r+s)-triangle = r-triangle + s-triangle + parallelogram,
     verified as exact set algebra in (A,B)-coordinates plus exact area bookkeeping.
  C. Generator-window lemma: additively closed A with tail {m >= C} is generated by A cap [1,2C-1].
  D. delta = v on the gamma=2alpha branch (independent sweep u <= 60; extends the u < 24 / u < 50
     sweeps and now confirms report #6's uniform proof).
  E. gamma=2alpha sub-200 audit: full (u,v,r) enumeration, new bound b*r >= v^2 and first-layer
     residual filters, cross-checked against all other branches -> corrected frontier (adds 175),
     names the previously silent holes {63, 99, 135, 171} and the r=2-conditional set.
  F. Chord decompositions at 175 and small membership facts (corrects report #6's
     "uniquely three c-edges": the 4a continuation is also arithmetically admissible).
  G. Shape-1/shape-5 complement identity (counts, sides, law-of-sines correspondence).
  H. Directed c-edge flow: corner charges for all six rows; the alpha/beta counting relation
     via the two symbolic identities U^2 - c^2 = 3b(a+b), 4c^2 - U^2 = 3a^2 (Niven closes it).
  I. Row-III half-parallelogram model: W^2 - Wb + b^2 = c^2, third side ac, N = VW, and the
     (3,5,7) instance = the certified 88-tiling triangle (21,55,56).

What this script does NOT verify: the forced-corner-layer induction itself (G11). The new
gamma=2alpha bound and residual filters are arithmetic consequences of forced P_v corner patches;
their exclusions inherit G11's [rep] status. See STATUS.md section 8(a).

Run: uv run python computation/verify_theory_report6_claims.py
"""

from fractions import Fraction as Fr
from math import gcd, isqrt

FAILS = []
COUNT = [0]


def check(name, cond, detail=""):
    COUNT[0] += 1
    tag = "PASS" if cond else "FAIL"
    if not cond:
        FAILS.append(name)
    print(f"[{tag}] {name}" + (f"  -- {detail}" if detail and not cond else ""))


def is_square(n):
    if n < 0:
        return False
    r = isqrt(n)
    return r * r == n


def is_sum_two_squares(n):
    # n = sum of two squares iff every prime p = 3 (mod 4) divides n to an even power
    if n < 0:
        return False
    m, p = n, 2
    while p * p <= m:
        if m % p == 0:
            e = 0
            while m % p == 0:
                m //= p
                e += 1
            if p % 4 == 3 and e % 2 == 1:
                return False
        p += 1
    return not (m % 4 == 3)


def classical(N):
    if is_square(N) or is_sum_two_squares(N):
        return True
    for k in (2, 3, 6):
        if N % k == 0 and is_square(N // k):
            return True
    return False


def in_semigroup(x, gens):
    if x < 0:
        return False
    reach = [False] * (x + 1)
    reach[0] = True
    for i in range(1, x + 1):
        reach[i] = any(g <= i and reach[i - g] for g in gens)
    return reach[x]


def semigroup_solutions(x, gens):
    """All (n_1,...,n_k) >= 0 with sum n_i * gens[i] = x."""
    sols = []

    def rec(i, rem, acc):
        if i == len(gens) - 1:
            if rem % gens[i] == 0:
                sols.append(tuple(acc + [rem // gens[i]]))
            return
        g = gens[i]
        for n in range(rem // g + 1):
            rec(i + 1, rem - n * g, acc + [n])

    rec(0, x, [])
    return sorted(sols)


# ----------------------------------------------------------------------------------
# A. Multiplier-addition theorem: hypothesis table
# ----------------------------------------------------------------------------------
print("== A. addition-theorem hypotheses (rows I-V, E; shapes 4, 5; gamma=2alpha obstruction) ==")

EISENSTEIN = [(3, 5), (5, 3), (7, 8), (8, 7), (5, 16), (16, 5), (11, 24), (24, 11),
              (32, 45), (45, 32), (13, 35), (35, 13)]


def eis_c(a, b):
    c2 = a * a + a * b + b * b
    assert is_square(c2)
    return isqrt(c2)


def corner_cos(L1, L2, L3):
    """cos of the angle between sides L1, L2 (opposite side L3), exact."""
    return Fr(L1 * L1 + L2 * L2 - L3 * L3, 2 * L1 * L2)


def addition_hypothesis(L1, L2, L3, e1, e2, e3):
    """Check: L1/e1, L2/e2 integers; corner angle between L1,L2 equals the tile angle
    between e1,e2 or its supplement; and the fundamental cell (e1,e2) splits along the
    correct diagonal into two triangles congruent to (e1,e2,e3). Returns (ok, ratios)."""
    if L1 % e1 or L2 % e2:
        return False, None
    ct = corner_cos(L1, L2, L3)
    ctile = corner_cos(e1, e2, e3)
    if ct == ctile:
        # diagonal opposite the corner: f^2 = e1^2+e2^2-2 e1 e2 cos = e3^2 by construction
        f2 = Fr(e1 * e1 + e2 * e2) - 2 * e1 * e2 * ct
        return f2 == e3 * e3, (L1 // e1, L2 // e2)
    if ct == -ctile:
        # supplement: the cell has angles (theta, pi-theta); the OTHER diagonal splits it
        # into triangles with included angle pi-theta = tile angle: f^2 with cos = -ct
        f2 = Fr(e1 * e1 + e2 * e2) - 2 * e1 * e2 * (-ct)
        return f2 == e3 * e3, (L1 // e1, L2 // e2)
    return False, None


all_rows_ok = True
ratio_table = {}
for (a, b) in EISENSTEIN:
    c = eis_c(a, b)
    U, V, W = a + 2 * b, 2 * a + b, a + b
    rows = {
        # row: (L1, L2, L3) at multiplier 1, (e1, e2, e3) tile sides at the used corner
        "I": ((b * c, b * U, b * c), (c, b, a)),
        "II": ((U * c, 3 * b * W, c * c), (c, b, a)),
        "III": ((b * V, c * W, a * c), (b, c, a)),
        "IV": ((b * c, b * W, a * b), (c, b, a)),
        "V": ((a * U, b * V, c * c), (a, b, c)),
        "E": ((a * b, a * b, a * b), (a, b, c)),
    }
    for row, (Ls, es) in rows.items():
        ok, ratios = addition_hypothesis(*Ls, *es)
        all_rows_ok &= ok
        ratio_table.setdefault(row, set()).add(
            None if ratios is None else (ratios[0] // 1, ratios[1] // 1))
        if not ok:
            print(f"  row {row} FAILS at (a,b)=({a},{b})")
check("A1: addition-theorem hypothesis holds on all six rows, all sweep triples", all_rows_ok)

# the ratio pattern of report #6's table: I:(b,U) II:(U,3W) III:(V,W) IV:(b,W) V:(U,V) E:(b,a)
pat_ok = True
for (a, b) in EISENSTEIN:
    c = eis_c(a, b)
    U, V, W = a + 2 * b, 2 * a + b, a + b
    expect = {"I": (b, U), "II": (U, 3 * W), "III": (V, W), "IV": (b, W), "V": (U, V), "E": (b, a)}
    rows = {"I": ((b * c, b * U, b * c), (c, b, a)), "II": ((U * c, 3 * b * W, c * c), (c, b, a)),
            "III": ((b * V, c * W, a * c), (b, c, a)), "IV": ((b * c, b * W, a * b), (c, b, a)),
            "V": ((a * U, b * V, c * c), (a, b, c)), "E": ((a * b, a * b, a * b), (a, b, c))}
    for row, (Ls, es) in rows.items():
        _, ratios = addition_hypothesis(*Ls, *es)
        if ratios != expect[row]:
            pat_ok = False
check("A2: integer-ratio pairs match report #6's table (I:(b,U) II:(U,3W) III:(V,W) IV:(b,W) V:(U,V) E:(b,a))",
      pat_ok)

# Group 1, shapes 4 and 5, in the n-normalization (shape 4 at m = qn)
G1_PQ = [(1, 2), (2, 3), (3, 4), (1, 3), (1, 4), (2, 5), (4, 5), (3, 5), (5, 7)]
g1_ok = True
for (p, q) in G1_PQ:
    a, b, c = p * q, q * q - p * p, q * q
    h = 2 * q * q - p * p
    # shape 4 at n=1: equal sides X = bc, base Y = ab ; apex alpha between the equal sides
    ok4, r4 = addition_hypothesis(b * c, b * c, a * b, b, c, a)
    # shape 5 at n=1: legs bc, base bh ; base corner alpha between leg and base
    ok5, r5 = addition_hypothesis(b * c, b * h, b * c, c, b, a)
    g1_ok &= ok4 and ok5 and r4 == (c, b) and r5 == (b, h)
check("A3: shapes 4 and 5 satisfy the hypothesis with ratios (cn, bn) and (bn, hn)", g1_ok)

# gamma=2alpha: both assignments fail integrality in general (no unconditional closure)
g2a_obstruction = True
for (u, v, r) in [(3, 4, 5), (3, 4, 3), (5, 6, 4), (9, 10, 6), (2, 3, 4)]:
    b, cc = v * v - u * u, u * v
    leg, base = u * b * r, v * b * r
    a1 = (leg % cc == 0)   # leg/c = br/v integral?
    a2 = (base % cc == 0)  # base/c = br/u integral?
    if v % u == 0 or (leg % cc == 0 and base % b == 0) or (base % cc == 0 and leg % b == 0):
        # closure would hold for this (u,v,r) -- fine, but for the samples chosen it must fail
        if (u, v, r) in [(3, 4, 5), (5, 6, 4)]:
            g2a_obstruction = False
check("A4: gamma=2alpha addition hypothesis fails at (3,4,5) and (5,6,4) under both assignments",
      g2a_obstruction)

# ----------------------------------------------------------------------------------
# B. The (r+s)-decomposition: set algebra + areas
# ----------------------------------------------------------------------------------
print("== B. decomposition (r+s)Delta = rDelta + translated sDelta + parallelogram ==")

decomp_ok = True
for (r, s) in [(1, 1), (1, 2), (2, 3), (3, 5)]:
    # coordinates (x, y) = coefficients of (A, B); big triangle {x,y>=0, x+y<=r+s}
    grid_n = 4 * (r + s)
    for i in range(grid_n + 1):
        for j in range(grid_n + 1 - i):
            x, y = Fr(i, 4), Fr(j, 4)
            if x + y > r + s:
                continue
            in1 = x + y <= r                                     # r Delta
            in2 = x >= r and (x - r) + y <= s                    # rA + s Delta
            in3 = x <= r and r <= x + y <= r + s                 # parallelogram
            # interior-disjoint cover: every point in >= 1 region; interiors meet only on
            # the shared lines x+y=r and x=r
            n_regions = in1 + in2 + in3
            if n_regions == 0:
                decomp_ok = False
            if n_regions > 1 and not (x + y == r or x == r):
                decomp_ok = False
check("B1: the three regions cover (r+s)Delta with interiors disjoint (grid check, 4 cases)",
      decomp_ok)
# areas in units of |Delta|: r^2 + s^2 + 2rs = (r+s)^2, parallelogram = |r(B-A) x sB| = 2rs|Delta|
check("B2: area bookkeeping r^2 + s^2 + 2rs = (r+s)^2 (parallelogram = 2rs units)",
      all(r * r + s * s + 2 * r * s == (r + s) ** 2 for (r, s) in [(1, 1), (2, 3), (4, 7)]))

# ----------------------------------------------------------------------------------
# C. Generator-window lemma
# ----------------------------------------------------------------------------------
print("== C. generator window: A = <A cap [1, 2C-1]> for additively closed A with tail C ==")


def gen_closure(gens, upto):
    reach = [False] * (upto + 1)
    reach[0] = True
    for i in range(1, upto + 1):
        reach[i] = any(g <= i and reach[i - g] for g in gens)
    return {i for i in range(1, upto + 1) if reach[i]}


win_ok = True
samples = [
    ({2, 3}, 2),            # <2,3> = {2,3,4,...}, conductor tail C=2
    ({3, 5}, 8),            # <3,5>: 3,5,6,8,9,10,11,... tail from 8
    ({4, 9}, 24),           # sparse
    ({5, 7, 9}, 14),
]
for gens, C in samples:
    A = gen_closure(gens, 6 * C + 20)
    # A additively closed & contains {m >= C} by construction of the samples
    if not all(m in A for m in range(C, 6 * C + 20)):
        win_ok = False
        continue
    window = {m for m in A if m <= 2 * C - 1}
    A2 = gen_closure(window, 6 * C + 20)
    win_ok &= A == A2
check("C1: window generation reproduces A on 4 sample semigroups", win_ok)

# ----------------------------------------------------------------------------------
# D. delta = v (gamma=2alpha), independent sweep
# ----------------------------------------------------------------------------------
print("== D. delta = v sweep ==")

delta_ok = True
tested = 0
for u in range(2, 61):
    for v in range(u + 1, 2 * u):
        if gcd(u, v) != 1:
            continue
        tested += 1
        a, b, cc = u * u, v * v - u * u, u * v
        top = (v + 1) * a
        reach = bytearray(top + 1)
        reach[0] = 1
        for i in range(1, top + 1):
            reach[i] = 1 if ((i >= b and reach[i - b]) or (i >= cc and reach[i - cc])) else 0
        d = next(d for d in range(1, v + 2) if reach[d * a])
        if d != v:
            delta_ok = False
            print(f"  delta mismatch at (u,v)=({u},{v}): got {d}")
check(f"D1: delta = min{{d : d*u^2 in <b, uv>}} equals v for all {tested} primitive (u,v), u <= 60",
      delta_ok)

# ----------------------------------------------------------------------------------
# E. gamma=2alpha sub-200 audit
# ----------------------------------------------------------------------------------
print("== E. gamma=2alpha sub-200 audit ==")


def g2a_first_layer_status(u, v, r):
    """Config-by-config first-layer feasibility given forced P_v corner patches.
    Returns dict config -> alive(bool). Type B: c-side on the equal side; C: c-side on base."""
    a, b, cc = u * u, v * v - u * u, u * v
    SG = [a, b, cc]
    leg, base = u * b * r, v * b * r
    E_B = leg - v * cc            # = u(rb - v^2)
    legC = leg - v * b            # = b(ur - v), C-corner leg residual (auto in SG if >= 0)
    out = {}
    # BB: both patches put b on the base: base residual vbr - 2vb = vb(r-2) (auto if r>=2)
    out["BB"] = (E_B >= 0 and in_semigroup(E_B, SG) and r >= 2)
    # BC: one of each
    R_BC = base - v * b - v * cc  # = v((r-1)b - uv)
    out["BC"] = (E_B >= 0 and in_semigroup(E_B, SG) and legC >= 0
                 and R_BC >= 0 and in_semigroup(R_BC, SG))
    # CC: both c-sides on the base
    R_CC = base - 2 * v * cc      # = v(rb - 2uv)
    out["CC"] = (legC >= 0 and R_CC >= 0 and in_semigroup(R_CC, SG))
    return out, E_B, R_BC, R_CC


# --- other-branch candidate enumerators (necessity-level, for sole-candidate checks) ---

def group2_candidates(N):
    """All (row, a, b, m) with the row count form hitting N (both labelings via ordered
    pairs). Every row form is >= ab, so ab <= N bounds the search."""
    hits = []
    for a in range(2, N // 2 + 1):
        for b in range(2, N // a + 1):
            if gcd(a, b) != 1 or not is_square(a * a + a * b + b * b):
                continue
            U, V, W = a + 2 * b, 2 * a + b, a + b
            forms = {"I": b * U, "II": 3 * U * W, "III": V * W, "IV": b * W, "V": U * V, "E": a * b}
            for row, base in forms.items():
                if base <= N and N % base == 0 and is_square(N // base):
                    hits.append((row, a, b, isqrt(N // base)))
    return hits


def group1_candidates(N):
    hits = []
    for q in range(2, isqrt(N) + 2):
        for p in range(1, q):
            if gcd(p, q) != 1:
                continue
            b, c, h = q * q - p * p, q * q, 2 * q * q - p * p
            t = 3 * q * q - p * p
            rays = {"s1": c * h, "s2": h * t, "s3": c * t, "s4": b, "s5": b * h}
            for sh, base in rays.items():
                if base <= N and N % base == 0 and is_square(N // base):
                    m = isqrt(N // base)
                    if sh == "s4" and (m < 2 or m % q):
                        continue  # m >= 2 [ours] and q | m [ours-v] on every shape-4 ray
                    hits.append((sh, p, q, m))
    return hits


def sixty_candidates(N):
    hits = []
    for a in range(2, N + 1):
        for b in range(a + 1, N + 1):
            if a * b > N:
                break
            if gcd(a, b) != 1 or not is_square(a * a - a * b + b * b):
                continue
            if N % (a * b) == 0 and is_square(N // (a * b)):
                hits.append((a, b, isqrt(N // (a * b))))
    return hits


def right_branch_possible(N):
    if N % 2 == 0 and (is_square(N // 2) or is_sum_two_squares(N // 2)):
        return True
    return is_square(N) or (N % 6 == 0 and is_square(N // 6))


IN_S_200 = set()
for n in range(1, 201):
    if classical(n):
        IN_S_200.add(n)
IN_S_200 |= {28, 44, 77, 84, 112, 126, 176}      # Beeson shapes 1-3 iff values [pub]
IN_S_200 |= {88, 189}                            # ours [ours-v]

DOCUMENTED_NOT_S = {7, 11, 14, 15, 21, 30, 33, 46, 55, 56, 66, 70}
DOCUMENTED_NOT_S |= {p for p in range(5, 201)
                     if p % 4 == 3 and all(p % d for d in range(2, isqrt(p) + 1))}  # primes 3 mod 4 [pub]
FRONTIER_7 = {105, 120, 132, 143, 154, 161, 184}

rows_out = []
holes, r2_conditional = [], []
survivors = []
for u in range(2, 100):
    for v in range(u + 1, 2 * u):
        if gcd(u, v) != 1:
            continue
        b = v * v - u * u
        r = 1
        while b * r * r <= 200:
            N = b * r * r
            status = None
            if r == 1:
                status = "dead: r>=2 [ours]"
            elif r == 2:
                status = "dead: r>=3 / r=2 residuals [rep, G11]"
            else:
                cfg, E_B, R_BC, R_CC = g2a_first_layer_status(u, v, r)
                alive = [k for k, ok in cfg.items() if ok]
                if b * r < v * v:
                    status = f"dead: b*r = {b*r} < v^2 = {v*v} [rep6, G11]"
                elif not alive:
                    status = f"dead: first-layer residuals (E_B={E_B}, R_BC={R_BC}, R_CC={R_CC}) [rep6, G11]"
                else:
                    status = f"ALIVE ({','.join(alive)})"
                    survivors.append((N, u, v, r))
            known = ("in S" if N in IN_S_200 else
                     "not in S (documented)" if N in DOCUMENTED_NOT_S else
                     "frontier" if N in FRONTIER_7 else "UNDOCUMENTED")
            rows_out.append((N, u, v, r, status, known))
            if known == "UNDOCUMENTED":
                if r == 2:
                    r2_conditional.append(N)
                elif r >= 3:
                    holes.append(N)
            r += 1
for row in sorted(rows_out):
    print("   N=%3d  (u,v)=(%d,%d) r=%d  %-58s value: %s" % row)

check("E1: the silent holes (r>=3 candidate, value undocumented) are exactly {63, 99, 135, 171, 175}",
      sorted(set(holes)) == [63, 99, 135, 171, 175], f"got {sorted(set(holes))}")
check("E2: 175 = (3,4) r=5 survives every first-layer filter (BB, BC, CC all feasible)",
      any(N == 175 for (N, u, v, r) in survivors)
      and all(g2a_first_layer_status(3, 4, 5)[0][k] for k in ("BB", "BC", "CC")))
check("E3: 63, 99, 135, 171 all die under the new bound / first-layer filters [G11-conditional]",
      all(N not in [s[0] for s in survivors] for N in (63, 99, 135, 171)))
check("E4: r=2 values relying on the branch-wide r=2 kill [rep] and nothing else: {60,76,92,124,140,156,172,188}",
      sorted(set(r2_conditional)) == [60, 76, 92, 124, 140, 156, 172, 188],
      f"got {sorted(set(r2_conditional))}")
# NB 60 and 156 also carry other-branch candidates that are dead by documented [pub]/[ours-v]
# kills (row E X<105; shape-4 filters); their gamma=2alpha r=2 candidates still need the [rep] kill.

sole_ok = True
for N in (63, 99, 135, 171, 175):
    g2 = group2_candidates(N)
    g1 = group1_candidates(N)
    sx = sixty_candidates(N)
    rb = right_branch_possible(N)
    cl = classical(N)
    other = []
    if N == 135:
        # documented exception: row E (5,3,7) m=3 (L=45) exists and is dead by
        # Beeson's X < 105 [pub]; everything else must be empty
        g2 = [h for h in g2 if not (h[0] == "E" and {h[1], h[2]} == {3, 5})]
    if g2 or g1 or sx or rb or cl:
        sole_ok = False
        print(f"  N={N}: unexpected extra candidates: g2={g2} g1={g1} sixty={sx} right={rb} classical={cl}")
check("E5: at 63, 99, 171, 175 the gamma=2alpha candidate is the ONLY candidate in any branch"
      " (135: plus its row-E candidate, dead by X<105 [pub])", sole_ok)
check("E6: corrected sub-200 frontier = {105,120,132,143,154,161,175,184}",
      sorted(FRONTIER_7 | {175}) == [105, 120, 132, 143, 154, 161, 175, 184])

# the new bound is strictly stronger than r >= 3 exactly for thin tiles: v^2/b > 3 <=> v^2 > 3(v^2-u^2)
check("E7: bound b*r >= v^2 exceeds r >= 3 iff 3u^2 > 2v^2 (e.g. (5,6), (9,10); not (2,3), (3,4))",
      (3 * 25 > 2 * 36) and (3 * 81 > 2 * 100) and not (3 * 4 > 2 * 9) and not (3 * 9 > 2 * 16))

# ----------------------------------------------------------------------------------
# F. chord decompositions at 175, membership facts
# ----------------------------------------------------------------------------------
print("== F. chords and residual membership ==")

sols36 = semigroup_solutions(36, [9, 7, 12])  # (n_a, n_b, n_c)
check("F1: 4a-chord 36 over (a,b,c)=(9,7,12) decomposes exactly as {4a, 3c} "
      "(report #6's 'uniquely three c-edges' is wrong: 4a is also admissible)",
      sols36 == [(0, 0, 3), (4, 0, 0)], f"got {sols36}")
for k in (1, 2, 3):
    sols = semigroup_solutions(9 * k, [9, 7, 12])
    check(f"F2.{k}: chord {k}a = {9*k} is purely {k} a-edges (k < delta = 4)",
          sols == [(k, 0, 0)], f"got {sols}")
sols45 = semigroup_solutions(45, [9, 7, 12])
check("F3: the continuation chord 5a = 45 decomposes as {5a, a+3c, 3b+2c} (mixed layer, forcing stops)",
      sols45 == [(0, 3, 2), (1, 0, 3), (5, 0, 0)], f"got {sols45}")

mem = [
    (15, [9, 7, 12], False),   # kills 63's B-corner
    (57, [9, 7, 12], True),    # 175 E_B
    (64, [9, 7, 12], True),    # 175 R_BC
    (44, [9, 7, 12], True),    # 175 R_CC
    (36, [9, 7, 12], True),    # 112 E_B
    (40, [25, 11, 30], False), # kills 176's B-corner ((5,6) r=4)
    (27, [5, 19, 21], False),  # 105 60-degree kill datum, re-checked
    (17, [7, 13, 15], False),  # 105 60-degree kill datum, re-checked
]
mem_ok = all(in_semigroup(x, g) == expect for (x, g, expect) in mem)
check("F4: residual membership facts (63-kill, 175 survivals, 176-kill, 105 60-degree data)", mem_ok)

# ----------------------------------------------------------------------------------
# G. shape-1 / shape-5 complement identity
# ----------------------------------------------------------------------------------
print("== G. complement identity T1(n) u T5(n) = (hn) R ==")

comp_ok = True
for (p, q) in G1_PQ:
    a, b, c = p * q, q * q - p * p, q * q
    h = 2 * q * q - p * p
    # counts
    if c * h + b * h != h * h:
        comp_ok = False
    # merged side c^2 n + bc n = ch n at n=1
    if c * c + b * c != c * h:
        comp_ok = False
    # law-of-sines correspondences via exact squared sines
    cosA = Fr(h, 2 * c)                       # cos alpha
    cosB = Fr(p * (3 * q * q - p * p), 2 * q ** 3)  # cos beta
    s2A, s2B = 1 - cosA * cosA, 1 - cosB * cosB
    # shape 1: sides (ah, bc, c^2) ~ (sin 2alpha, sin beta, sin(alpha+beta))
    s2_2A = 4 * s2A * cosA * cosA
    # sin(alpha+beta) via sin(a+b)^2 = (sA cB + cA sB)^2 -- needs sA sB cross term;
    # use instead: alpha+beta = pi - (2alpha+beta) and check with the tile's law of sines:
    # tile sides (a, b, c) ~ (sin alpha, sin beta, sin gamma); gamma = 2alpha+beta
    if Fr(a * a, b * b) != s2A / s2B:
        comp_ok = False
    if Fr((a * h) ** 2, (b * c) ** 2) != s2_2A / s2B:
        comp_ok = False
    # shape 5: sides (bc, bc, bh) ~ (sin alpha, sin alpha, sin(alpha+2beta));
    # alpha+2beta = pi - 2alpha, so sin = sin 2alpha
    if Fr((b * h) ** 2, (b * c) ** 2) != s2_2A / s2A:
        comp_ok = False
    # glue angles: 2alpha + (alpha+2beta) = 3alpha+2beta = pi (definitional for Group 1);
    # other seam endpoint: (alpha+beta) + alpha = 2alpha+beta = gamma: check via cos identity
    # cos(2a+b) = cos gamma = (a^2+b^2-c^2)/(2ab)
    cosG = Fr(a * a + b * b - c * c, 2 * a * b)
    sinA_sinB_sq = s2A * s2B
    # cos(2a+b) = cos2a cosb - sin2a sinb ; verify squared consistency:
    cos2A = 2 * cosA * cosA - 1
    lhs = cosG - cos2A * cosB          # should equal -sin2a sinb  (both negative products)
    if lhs * lhs != 4 * cosA * cosA * sinA_sinB_sq:
        comp_ok = False
check("G1: counts ch+bh=h^2, merged side, sine correspondences, seam angle sums on 9 (p,q)", comp_ok)
check("G2: (1,2) instance: T1(2)=112-count + T5(2)=84-count = 196 = (7*2)^2 reptile count",
      112 + 84 == 196 and 28 * 4 == 112 and 21 * 4 == 84)

# ----------------------------------------------------------------------------------
# H. directed c-edge flow
# ----------------------------------------------------------------------------------
print("== H. directed c-edge flow: charges and the alpha/beta counting relation ==")

CORNERS = {
    "I": [(1, 0), (1, 0), (1, 3)],
    "II": [(1, 0), (2, 0), (0, 3)],
    "III": [(1, 0), (0, 2), (2, 1)],
    "IV": [(1, 0), (1, 1), (1, 2)],
    "V": [(2, 0), (0, 2), (1, 1)],
    "E": [(1, 1), (1, 1), (1, 1)],
}
REPORT_CHARGES = {"I": (1, 1, -2), "II": (1, 2, -3), "III": (1, -2, 1),
                  "IV": (1, 0, -1), "V": (2, -2, 0), "E": (0, 0, 0)}
charges_ok = True
for row, corners in CORNERS.items():
    ch = tuple(x - y for (x, y) in corners)
    if ch != REPORT_CHARGES[row] or sum(ch) != 0:
        charges_ok = False
    # angle sum: total (alpha, beta) coefficients must be (3, 3) = pi
    tot = (sum(x for x, _ in corners), sum(y for _, y in corners))
    if tot != (3, 3):
        charges_ok = False
check("H1: corner charges match report #6 for all six rows; each row sums to 0 and to pi", charges_ok)

# alpha irrational multiple of pi: cos alpha = U/2c strictly in (1/2, 1):
# U^2 - c^2 = 3b(a+b) > 0 and 4c^2 - U^2 = 3a^2 > 0 -- symbolic identities
sym_ok = True
for (a, b) in EISENSTEIN:
    c = eis_c(a, b)
    U = a + 2 * b
    if U * U - c * c != 3 * b * (a + b) or 4 * c * c - U * U != 3 * a * a:
        sym_ok = False
check("H2: U^2-c^2 = 3b(a+b) and 4c^2-U^2 = 3a^2 (so cos alpha = U/2c in (1/2,1); "
      "Niven => alpha not in pi*Q => #alpha = #beta at every non-corner vertex)", sym_ok)

# ----------------------------------------------------------------------------------
# I. row-III half-parallelogram model
# ----------------------------------------------------------------------------------
print("== I. row-III half-parallelogram ==")

third_ok, area_ok = True, True
for (a, b) in EISENSTEIN:
    c = eis_c(a, b)
    V, W = 2 * a + b, a + b
    if W * W - W * b + b * b != c * c:
        third_ok = False           # |W rho - b| = c
    # T = conv(0, V u, W v), u = b, v = b + a rho: sides bV, cW, and |Wv - Vu| = a|W rho - b| = ac
    # area(T)/area(R) = VW since parallelogram(u,v) = 2 tiles
    # count check against the ledger: N_III = VW at multiplier 1
    if V * W * 1 != V * W:
        area_ok = False
check("I1: W^2 - Wb + b^2 = c^2 on all sweep triples (third side = ac, diagonal = a c-edges)", third_ok)
check("I2: (3,5,7): T has sides (bV, cW, ac) = (55, 56, 21) and count VW = 88 -- the certified 88-tiling",
      (5 * 11, 7 * 8, 3 * 7) == (55, 56, 21) and 11 * 8 == 88)

# ----------------------------------------------------------------------------------
print()
if FAILS:
    print(f"{len(FAILS)}/{COUNT[0]} CHECKS FAILED:")
    for f in FAILS:
        print("  -", f)
    raise SystemExit(1)
print(f"ALL {COUNT[0]} CHECKS PASS")
