import PeaceableQueens.UpperBound.FiniteCutTable

/-! Generated by scripts/generate_fast_finite_tables.py.

Pinned recovered benders76 SHA-256: ad960316bc8099e4be3e0d585abb472c6a7e81d2963ee65f79457d7161d5a96a

This checked execution table uses direct Array
literals, not arrays materialized from `FiniteCertificates.cuts`; the theorems
below re-establish equality to the proof-facing table in the kernel.
-/

namespace PeaceableQueens.UpperBound.FastFiniteTables

open FiniteLattice FiniteCertificates

structure FastCutData where
  constant : Int
  linear : Array Int
  bilinear : Array (Array Int)
  deriving Inhabited

private theorem cut_eq_of_components (a b : Cut 8)
    (h : a.constant = b.constant ∧
      (∀ i, a.linear i = b.linear i) ∧ ∀ i j, a.bilinear i j = b.bilinear i j) :
    a = b := by
  rcases h with ⟨hc, hl, hb⟩
  have hl' := funext hl
  have hb' := funext (fun i => funext (hb i))
  cases a
  cases b
  cases hc
  cases hl'
  cases hb'
  rfl

private theorem row_eq_of_components (a b : Row 8)
    (hc : a.coeff = b.coeff) (hr : a.rhs = b.rhs) : a = b := by
  cases a
  cases b
  cases hc
  cases hr
  rfl

/-- The recovered cuts as actual runtime arrays. -/
def fastCutData : Array FastCutData := #[
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 12, 12, 0, 0, 0, 0], #[0, 0, 12, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-24, -24, -24, -24, 0, 0, 0, 0], bilinear := #[#[0, 0, 12, 12, 0, 0, 0, 0], #[0, 0, 12, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-24, -24, 0, 0, -24, -24, 0, 0], bilinear := #[#[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-24, -24, 0, 0, 0, 0, -24, -24], bilinear := #[#[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[0, 0, -24, -24, -24, -24, 0, 0], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 12, 12, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[0, 0, -24, -24, 0, 0, -24, -24], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 12, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 0], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 24, 0], #[0, 0, 0, 0, 0, 0, 0, 24], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[0, 0, 0, 0, -24, -24, -24, -24], bilinear := #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 24, 0], #[0, 0, 0, 0, 0, 0, 0, 24], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 12, linear := #[-6, -6, -6, -6, -6, -6, -6, -6], bilinear := #[#[0, 0, 3, 3, 3, 3, 3, 3], #[0, 0, 3, 3, 3, 3, 3, 3], #[0, 0, 0, 0, 3, 3, 3, 3], #[0, 0, 0, 0, 3, 3, 3, 3], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-12, -12, -12, -12, -12, -12, -12, -12], bilinear := #[#[0, 0, 3, 3, 3, 3, 3, 3], #[0, 0, 3, 3, 3, 3, 3, 3], #[0, 0, 0, 0, 3, 3, 3, 3], #[0, 0, 0, 0, 3, 3, 3, 3], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 24, 0, 0], bilinear := #[#[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 0, 24], bilinear := #[#[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 24, 0, 0, 0], bilinear := #[#[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 0, linear := #[0, 0, 0, 0, 0, 0, 24, 0], bilinear := #[#[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-12, -12, -12, -12, 0, -24, 0, 0], bilinear := #[#[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-12, -12, -12, -12, 0, 0, 0, -24], bilinear := #[#[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-12, -12, -12, -12, -24, 0, 0, 0], bilinear := #[#[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 48, linear := #[-12, -12, -12, -12, 0, 0, -24, 0], bilinear := #[#[0, 0, 0, 12, 0, 0, 0, 0], #[0, 0, 12, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 0, 0, 6], #[0, 0, 0, 6, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 6, 0, 0], #[0, 0, 0, 6, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 0, 6, 0], #[0, 0, 6, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 0, 0, 0], #[0, 0, 6, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 0, 6, 0, 6, 6, 6], #[0, 0, 6, 6, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 0, 6, 6, 6, 0, 6], #[0, 0, 6, 6, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 0, 6, 0, 6, 6], #[0, 0, 6, 6, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 0, 6, 6, 6, 0], #[0, 0, 6, 6, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -6, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 0, 0, 6, 0, 0], #[0, 0, 6, 6, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -6, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 0, 0, 0, 0, 6], #[0, 0, 6, 6, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -6, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 6, 6, 6], #[0, 0, 6, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -6, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 6, 0, 6], #[0, 0, 6, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -6, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 0, 6, 6, 0, 0, 0], #[0, 0, 6, 6, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -6, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 0, 6, 0, 0, 6, 0], #[0, 0, 6, 6, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -6, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 0, 6, 6], #[0, 0, 0, 6, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -6, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 6, 6, 0], #[0, 0, 0, 6, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-6, -18, 0, -18, -18, 0, -18, -12], bilinear := #[#[0, 0, 6, 6, 0, 0, 0, 6], #[0, 0, 0, 6, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-6, -18, 0, -18, -18, -12, -18, 0], bilinear := #[#[0, 0, 6, 6, 0, 6, 0, 0], #[0, 0, 0, 6, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-6, -18, -18, 0, 0, -18, -12, -18], bilinear := #[#[0, 0, 6, 6, 0, 0, 6, 0], #[0, 0, 6, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-6, -18, -18, 0, -12, -18, 0, -18], bilinear := #[#[0, 0, 6, 6, 6, 0, 0, 0], #[0, 0, 6, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, -6, 0, -18, 0, -18, -12, -18], bilinear := #[#[0, 0, 0, 6, 0, 6, 6, 6], #[0, 0, 6, 6, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, -6, 0, -18, -12, -18, 0, -18], bilinear := #[#[0, 0, 0, 6, 6, 6, 0, 6], #[0, 0, 6, 6, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, -6, -18, 0, -18, 0, -18, -12], bilinear := #[#[0, 0, 6, 0, 6, 0, 6, 6], #[0, 0, 6, 6, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, -6, -18, 0, -18, -12, -18, 0], bilinear := #[#[0, 0, 6, 0, 6, 6, 6, 0], #[0, 0, 6, 6, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[0, -18, -6, -18, -18, 0, -18, -12], bilinear := #[#[0, 0, 6, 0, 0, 6, 0, 0], #[0, 0, 6, 6, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[0, -18, -6, -18, -18, -12, -18, 0], bilinear := #[#[0, 0, 6, 0, 0, 0, 0, 6], #[0, 0, 6, 6, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, 0, -6, -18, 0, -18, -12, -18], bilinear := #[#[0, 0, 6, 6, 0, 6, 6, 6], #[0, 0, 6, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, 0, -6, -18, -12, -18, 0, -18], bilinear := #[#[0, 0, 6, 6, 6, 6, 0, 6], #[0, 0, 6, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[0, -18, -18, -6, 0, -18, -12, -18], bilinear := #[#[0, 0, 0, 6, 6, 0, 0, 0], #[0, 0, 6, 6, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[0, -18, -18, -6, -12, -18, 0, -18], bilinear := #[#[0, 0, 0, 6, 0, 0, 6, 0], #[0, 0, 6, 6, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, 0, -18, -6, -18, 0, -18, -12], bilinear := #[#[0, 0, 6, 6, 6, 0, 6, 6], #[0, 0, 0, 6, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-18, 0, -18, -6, -18, -12, -18, 0], bilinear := #[#[0, 0, 6, 6, 6, 6, 6, 0], #[0, 0, 0, 6, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 12, linear := #[-6, -6, -6, -6, -6, 0, -6, -6], bilinear := #[#[0, 0, 3, 9, 3, 0, 3, 3], #[0, 0, 9, 3, 3, 0, 3, 3], #[0, 0, 0, 0, 3, 0, 3, 3], #[0, 0, 0, 0, 3, 0, 3, 3], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 12, linear := #[-6, -6, -6, -6, -6, -6, -6, 0], bilinear := #[#[0, 0, 3, 9, 3, 3, 3, 0], #[0, 0, 9, 3, 3, 3, 3, 0], #[0, 0, 0, 0, 3, 3, 3, 0], #[0, 0, 0, 0, 3, 3, 3, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 12, linear := #[-6, -6, -6, -6, 0, -6, -6, -6], bilinear := #[#[0, 0, 9, 3, 0, 3, 3, 3], #[0, 0, 3, 9, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 12, linear := #[-6, -6, -6, -6, -6, -6, 0, -6], bilinear := #[#[0, 0, 9, 3, 3, 3, 0, 3], #[0, 0, 3, 9, 3, 3, 0, 3], #[0, 0, 0, 0, 3, 3, 0, 3], #[0, 0, 0, 0, 3, 3, 0, 3], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-15, -15, -15, -15, -12, 0, -12, -6], bilinear := #[#[0, 0, 3, 9, 3, 0, 3, 3], #[0, 0, 9, 3, 3, 0, 3, 3], #[0, 0, 0, 0, 3, 0, 3, 3], #[0, 0, 0, 0, 3, 0, 3, 3], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-15, -15, -15, -15, -12, -6, -12, 0], bilinear := #[#[0, 0, 3, 9, 3, 3, 3, 0], #[0, 0, 9, 3, 3, 3, 3, 0], #[0, 0, 0, 0, 3, 3, 3, 0], #[0, 0, 0, 0, 3, 3, 3, 0], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-15, -15, -15, -15, 0, -12, -6, -12], bilinear := #[#[0, 0, 9, 3, 0, 3, 3, 3], #[0, 0, 3, 9, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 3, 3, 3], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 36, linear := #[-15, -15, -15, -15, -6, -12, 0, -12], bilinear := #[#[0, 0, 9, 3, 3, 3, 0, 3], #[0, 0, 3, 9, 3, 3, 0, 3], #[0, 0, 0, 0, 3, 3, 0, 3], #[0, 0, 0, 0, 3, 3, 0, 3], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -6, -6, -6, -12, -12, -12, -12], bilinear := #[#[0, 0, 0, 0, 0, 6, 0, 6], #[0, 0, 0, 0, 0, 6, 0, 6], #[0, 0, 0, 0, 6, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -6, -6, -6, -12, -12, -12, -12], bilinear := #[#[0, 0, 0, 0, 6, 0, 6, 0], #[0, 0, 0, 0, 6, 0, 6, 0], #[0, 0, 0, 0, 0, 6, 0, 6], #[0, 0, 0, 0, 0, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -6, -12, -6, -12, -6], bilinear := #[#[0, 0, 0, 6, 0, 0, 0, 6], #[0, 0, 6, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -12, -6, -12, -6, -12, -6], bilinear := #[#[0, 0, 0, 6, 0, 6, 0, 0], #[0, 0, 6, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -6, -12, -6, -12, -6, -12], bilinear := #[#[0, 0, 6, 0, 0, 0, 6, 0], #[0, 0, 0, 6, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-6, -12, -6, -12, -6, -12, -6, -12], bilinear := #[#[0, 0, 6, 0, 6, 0, 0, 0], #[0, 0, 0, 6, 0, 6, 6, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -6, -6, -12, -6, -12], bilinear := #[#[0, 0, 6, 0, 6, 6, 0, 6], #[0, 0, 0, 6, 0, 0, 6, 0], #[0, 0, 0, 0, 6, 6, 0, 6], #[0, 0, 0, 0, 0, 0, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -12, -6, -6, -12, -6, -12], bilinear := #[#[0, 0, 6, 0, 0, 6, 6, 6], #[0, 0, 0, 6, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 6, 6, 6], #[0, 0, 0, 0, 6, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 12], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -6, -12, -12, -6, -12, -6], bilinear := #[#[0, 0, 0, 6, 6, 6, 6, 0], #[0, 0, 6, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 6], #[0, 0, 0, 0, 6, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -6, -6, -12, -12, -6, -12, -6], bilinear := #[#[0, 0, 0, 6, 6, 0, 6, 6], #[0, 0, 6, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 0, 6, 0, 0], #[0, 0, 0, 0, 6, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 12, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 0, 6, 6], #[0, 0, 6, 6, 6, 6, 0, 0], #[0, 0, 0, 0, 0, 6, 6, 0], #[0, 0, 0, 0, 6, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 6, 0, 0], #[0, 0, 6, 6, 0, 0, 6, 6], #[0, 0, 0, 0, 6, 0, 0, 6], #[0, 0, 0, 0, 0, 6, 6, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 0, 6, 6, 0], #[0, 0, 6, 6, 6, 0, 0, 6], #[0, 0, 0, 0, 0, 0, 6, 6], #[0, 0, 0, 0, 6, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] },
  { constant := 24, linear := #[-12, -12, -12, -12, -6, -6, -6, -6], bilinear := #[#[0, 0, 6, 6, 6, 0, 0, 6], #[0, 0, 6, 6, 0, 6, 6, 0], #[0, 0, 0, 0, 6, 6, 0, 0], #[0, 0, 0, 0, 0, 0, 6, 6], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0]] }
]

/-- Present an array-backed cut through the established `Cut` interface. -/
def fastCuts : Fin 76 → Cut 8 := fun c =>
  let data := fastCutData[c.val]!
  { constant := data.constant,
     linear := fun i => data.linear[i.val]!,
     bilinear := fun i j => (data.bilinear[i.val]!)[j.val]! }

theorem fastCut_00_eq : fastCuts 0 = cuts 0 := by
  apply cut_eq_of_components
  decide

theorem fastCut_01_eq : fastCuts 1 = cuts 1 := by
  apply cut_eq_of_components
  decide

theorem fastCut_02_eq : fastCuts 2 = cuts 2 := by
  apply cut_eq_of_components
  decide

theorem fastCut_03_eq : fastCuts 3 = cuts 3 := by
  apply cut_eq_of_components
  decide

theorem fastCut_04_eq : fastCuts 4 = cuts 4 := by
  apply cut_eq_of_components
  decide

theorem fastCut_05_eq : fastCuts 5 = cuts 5 := by
  apply cut_eq_of_components
  decide

theorem fastCut_06_eq : fastCuts 6 = cuts 6 := by
  apply cut_eq_of_components
  decide

theorem fastCut_07_eq : fastCuts 7 = cuts 7 := by
  apply cut_eq_of_components
  decide

theorem fastCut_08_eq : fastCuts 8 = cuts 8 := by
  apply cut_eq_of_components
  decide

theorem fastCut_09_eq : fastCuts 9 = cuts 9 := by
  apply cut_eq_of_components
  decide

theorem fastCut_10_eq : fastCuts 10 = cuts 10 := by
  apply cut_eq_of_components
  decide

theorem fastCut_11_eq : fastCuts 11 = cuts 11 := by
  apply cut_eq_of_components
  decide

theorem fastCut_12_eq : fastCuts 12 = cuts 12 := by
  apply cut_eq_of_components
  decide

theorem fastCut_13_eq : fastCuts 13 = cuts 13 := by
  apply cut_eq_of_components
  decide

theorem fastCut_14_eq : fastCuts 14 = cuts 14 := by
  apply cut_eq_of_components
  decide

theorem fastCut_15_eq : fastCuts 15 = cuts 15 := by
  apply cut_eq_of_components
  decide

theorem fastCut_16_eq : fastCuts 16 = cuts 16 := by
  apply cut_eq_of_components
  decide

theorem fastCut_17_eq : fastCuts 17 = cuts 17 := by
  apply cut_eq_of_components
  decide

theorem fastCut_18_eq : fastCuts 18 = cuts 18 := by
  apply cut_eq_of_components
  decide

theorem fastCut_19_eq : fastCuts 19 = cuts 19 := by
  apply cut_eq_of_components
  decide

theorem fastCut_20_eq : fastCuts 20 = cuts 20 := by
  apply cut_eq_of_components
  decide

theorem fastCut_21_eq : fastCuts 21 = cuts 21 := by
  apply cut_eq_of_components
  decide

theorem fastCut_22_eq : fastCuts 22 = cuts 22 := by
  apply cut_eq_of_components
  decide

theorem fastCut_23_eq : fastCuts 23 = cuts 23 := by
  apply cut_eq_of_components
  decide

theorem fastCut_24_eq : fastCuts 24 = cuts 24 := by
  apply cut_eq_of_components
  decide

theorem fastCut_25_eq : fastCuts 25 = cuts 25 := by
  apply cut_eq_of_components
  decide

theorem fastCut_26_eq : fastCuts 26 = cuts 26 := by
  apply cut_eq_of_components
  decide

theorem fastCut_27_eq : fastCuts 27 = cuts 27 := by
  apply cut_eq_of_components
  decide

theorem fastCut_28_eq : fastCuts 28 = cuts 28 := by
  apply cut_eq_of_components
  decide

theorem fastCut_29_eq : fastCuts 29 = cuts 29 := by
  apply cut_eq_of_components
  decide

theorem fastCut_30_eq : fastCuts 30 = cuts 30 := by
  apply cut_eq_of_components
  decide

theorem fastCut_31_eq : fastCuts 31 = cuts 31 := by
  apply cut_eq_of_components
  decide

theorem fastCut_32_eq : fastCuts 32 = cuts 32 := by
  apply cut_eq_of_components
  decide

theorem fastCut_33_eq : fastCuts 33 = cuts 33 := by
  apply cut_eq_of_components
  decide

theorem fastCut_34_eq : fastCuts 34 = cuts 34 := by
  apply cut_eq_of_components
  decide

theorem fastCut_35_eq : fastCuts 35 = cuts 35 := by
  apply cut_eq_of_components
  decide

theorem fastCut_36_eq : fastCuts 36 = cuts 36 := by
  apply cut_eq_of_components
  decide

theorem fastCut_37_eq : fastCuts 37 = cuts 37 := by
  apply cut_eq_of_components
  decide

theorem fastCut_38_eq : fastCuts 38 = cuts 38 := by
  apply cut_eq_of_components
  decide

theorem fastCut_39_eq : fastCuts 39 = cuts 39 := by
  apply cut_eq_of_components
  decide

theorem fastCut_40_eq : fastCuts 40 = cuts 40 := by
  apply cut_eq_of_components
  decide

theorem fastCut_41_eq : fastCuts 41 = cuts 41 := by
  apply cut_eq_of_components
  decide

theorem fastCut_42_eq : fastCuts 42 = cuts 42 := by
  apply cut_eq_of_components
  decide

theorem fastCut_43_eq : fastCuts 43 = cuts 43 := by
  apply cut_eq_of_components
  decide

theorem fastCut_44_eq : fastCuts 44 = cuts 44 := by
  apply cut_eq_of_components
  decide

theorem fastCut_45_eq : fastCuts 45 = cuts 45 := by
  apply cut_eq_of_components
  decide

theorem fastCut_46_eq : fastCuts 46 = cuts 46 := by
  apply cut_eq_of_components
  decide

theorem fastCut_47_eq : fastCuts 47 = cuts 47 := by
  apply cut_eq_of_components
  decide

theorem fastCut_48_eq : fastCuts 48 = cuts 48 := by
  apply cut_eq_of_components
  decide

theorem fastCut_49_eq : fastCuts 49 = cuts 49 := by
  apply cut_eq_of_components
  decide

theorem fastCut_50_eq : fastCuts 50 = cuts 50 := by
  apply cut_eq_of_components
  decide

theorem fastCut_51_eq : fastCuts 51 = cuts 51 := by
  apply cut_eq_of_components
  decide

theorem fastCut_52_eq : fastCuts 52 = cuts 52 := by
  apply cut_eq_of_components
  decide

theorem fastCut_53_eq : fastCuts 53 = cuts 53 := by
  apply cut_eq_of_components
  decide

theorem fastCut_54_eq : fastCuts 54 = cuts 54 := by
  apply cut_eq_of_components
  decide

theorem fastCut_55_eq : fastCuts 55 = cuts 55 := by
  apply cut_eq_of_components
  decide

theorem fastCut_56_eq : fastCuts 56 = cuts 56 := by
  apply cut_eq_of_components
  decide

theorem fastCut_57_eq : fastCuts 57 = cuts 57 := by
  apply cut_eq_of_components
  decide

theorem fastCut_58_eq : fastCuts 58 = cuts 58 := by
  apply cut_eq_of_components
  decide

theorem fastCut_59_eq : fastCuts 59 = cuts 59 := by
  apply cut_eq_of_components
  decide

theorem fastCut_60_eq : fastCuts 60 = cuts 60 := by
  apply cut_eq_of_components
  decide

theorem fastCut_61_eq : fastCuts 61 = cuts 61 := by
  apply cut_eq_of_components
  decide

theorem fastCut_62_eq : fastCuts 62 = cuts 62 := by
  apply cut_eq_of_components
  decide

theorem fastCut_63_eq : fastCuts 63 = cuts 63 := by
  apply cut_eq_of_components
  decide

theorem fastCut_64_eq : fastCuts 64 = cuts 64 := by
  apply cut_eq_of_components
  decide

theorem fastCut_65_eq : fastCuts 65 = cuts 65 := by
  apply cut_eq_of_components
  decide

theorem fastCut_66_eq : fastCuts 66 = cuts 66 := by
  apply cut_eq_of_components
  decide

theorem fastCut_67_eq : fastCuts 67 = cuts 67 := by
  apply cut_eq_of_components
  decide

theorem fastCut_68_eq : fastCuts 68 = cuts 68 := by
  apply cut_eq_of_components
  decide

theorem fastCut_69_eq : fastCuts 69 = cuts 69 := by
  apply cut_eq_of_components
  decide

theorem fastCut_70_eq : fastCuts 70 = cuts 70 := by
  apply cut_eq_of_components
  decide

theorem fastCut_71_eq : fastCuts 71 = cuts 71 := by
  apply cut_eq_of_components
  decide

theorem fastCut_72_eq : fastCuts 72 = cuts 72 := by
  apply cut_eq_of_components
  decide

theorem fastCut_73_eq : fastCuts 73 = cuts 73 := by
  apply cut_eq_of_components
  decide

theorem fastCut_74_eq : fastCuts 74 = cuts 74 := by
  apply cut_eq_of_components
  decide

theorem fastCut_75_eq : fastCuts 75 = cuts 75 := by
  apply cut_eq_of_components
  decide

/-- The array-backed cut function agrees with the established table. -/
theorem fastCuts_eq : fastCuts = cuts := by
  funext c
  fin_cases c
  · exact fastCut_00_eq
  · exact fastCut_01_eq
  · exact fastCut_02_eq
  · exact fastCut_03_eq
  · exact fastCut_04_eq
  · exact fastCut_05_eq
  · exact fastCut_06_eq
  · exact fastCut_07_eq
  · exact fastCut_08_eq
  · exact fastCut_09_eq
  · exact fastCut_10_eq
  · exact fastCut_11_eq
  · exact fastCut_12_eq
  · exact fastCut_13_eq
  · exact fastCut_14_eq
  · exact fastCut_15_eq
  · exact fastCut_16_eq
  · exact fastCut_17_eq
  · exact fastCut_18_eq
  · exact fastCut_19_eq
  · exact fastCut_20_eq
  · exact fastCut_21_eq
  · exact fastCut_22_eq
  · exact fastCut_23_eq
  · exact fastCut_24_eq
  · exact fastCut_25_eq
  · exact fastCut_26_eq
  · exact fastCut_27_eq
  · exact fastCut_28_eq
  · exact fastCut_29_eq
  · exact fastCut_30_eq
  · exact fastCut_31_eq
  · exact fastCut_32_eq
  · exact fastCut_33_eq
  · exact fastCut_34_eq
  · exact fastCut_35_eq
  · exact fastCut_36_eq
  · exact fastCut_37_eq
  · exact fastCut_38_eq
  · exact fastCut_39_eq
  · exact fastCut_40_eq
  · exact fastCut_41_eq
  · exact fastCut_42_eq
  · exact fastCut_43_eq
  · exact fastCut_44_eq
  · exact fastCut_45_eq
  · exact fastCut_46_eq
  · exact fastCut_47_eq
  · exact fastCut_48_eq
  · exact fastCut_49_eq
  · exact fastCut_50_eq
  · exact fastCut_51_eq
  · exact fastCut_52_eq
  · exact fastCut_53_eq
  · exact fastCut_54_eq
  · exact fastCut_55_eq
  · exact fastCut_56_eq
  · exact fastCut_57_eq
  · exact fastCut_58_eq
  · exact fastCut_59_eq
  · exact fastCut_60_eq
  · exact fastCut_61_eq
  · exact fastCut_62_eq
  · exact fastCut_63_eq
  · exact fastCut_64_eq
  · exact fastCut_65_eq
  · exact fastCut_66_eq
  · exact fastCut_67_eq
  · exact fastCut_68_eq
  · exact fastCut_69_eq
  · exact fastCut_70_eq
  · exact fastCut_71_eq
  · exact fastCut_72_eq
  · exact fastCut_73_eq
  · exact fastCut_74_eq
  · exact fastCut_75_eq

structure FastRowData where
  coeff : Array Int
  rhsFactor : Int
  deriving Inhabited

/-- The five propagation rows, with their right-hand sides represented as a
constant factor of `q`. -/
def fastRowData : Array FastRowData := #[
  { coeff := #[1, -1, 0, 0, 0, 0, 0, 0], rhsFactor := 0 },
  { coeff := #[0, 0, 1, -1, 0, 0, 0, 0], rhsFactor := 0 },
  { coeff := #[1, 1, -1, -1, 0, 0, 0, 0], rhsFactor := 0 },
  { coeff := #[0, 0, 0, 0, 1, 1, -1, -1], rhsFactor := 0 },
  { coeff := #[1, 1, 1, 1, 1, 1, 1, 1], rhsFactor := 4 }
]

def fastDomainRows (q : Nat) : Fin 5 → Row 8 := fun row =>
  let data := fastRowData[row.val]!
  { coeff := fun i => data.coeff[i.val]!,
     rhs := data.rhsFactor * (q : Int) }

theorem fastDomainRow_0_eq (q : Nat) :
    fastDomainRows q 0 = domainRows q 0 := by
  apply row_eq_of_components
  · funext i
    fin_cases i <;> rfl
  · change (0 : Int) * (q : Int) = 0
    simp

theorem fastDomainRow_1_eq (q : Nat) :
    fastDomainRows q 1 = domainRows q 1 := by
  apply row_eq_of_components
  · funext i
    fin_cases i <;> rfl
  · change (0 : Int) * (q : Int) = 0
    simp

theorem fastDomainRow_2_eq (q : Nat) :
    fastDomainRows q 2 = domainRows q 2 := by
  apply row_eq_of_components
  · funext i
    fin_cases i <;> rfl
  · change (0 : Int) * (q : Int) = 0
    simp

theorem fastDomainRow_3_eq (q : Nat) :
    fastDomainRows q 3 = domainRows q 3 := by
  apply row_eq_of_components
  · funext i
    fin_cases i <;> rfl
  · change (0 : Int) * (q : Int) = 0
    simp

theorem fastDomainRow_4_eq (q : Nat) :
    fastDomainRows q 4 = domainRows q 4 := by
  apply row_eq_of_components
  · funext i
    fin_cases i <;> rfl
  · rfl

theorem fastDomainRows_eq (q : Nat) : fastDomainRows q = domainRows q := by
  funext row
  fin_cases row
  · exact fastDomainRow_0_eq q
  · exact fastDomainRow_1_eq q
  · exact fastDomainRow_2_eq q
  · exact fastDomainRow_3_eq q
  · exact fastDomainRow_4_eq q

/-- The fast table preserves the no-diagonal certificate by transport. -/
def fastCutTable : CutTable 8 76 := {
  cuts := fastCuts
  noDiagonal := by
    intro c
    rw [fastCuts_eq]
    exact cutTable.noDiagonal c
}

#print axioms fastCuts_eq
#print axioms fastDomainRows_eq
#print axioms fastCutTable

end PeaceableQueens.UpperBound.FastFiniteTables
