import PeaceableQueens.UpperBound.FastFiniteTables
import PeaceableQueens.UpperBound.IndependentCornerMax

/-! Generated by scripts/generate_independent_cut_masks.py.
Coefficient source SHA-256: ad960316bc8099e4be3e0d585abb472c6a7e81d2963ee65f79457d7161d5a96a
The optimization choice is untrusted data; independence is checked below.
-/

namespace PeaceableQueens.UpperBound.IndependentCutMasks

def table : Array (List (Fin 8)) := #[
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [2, 3],
  [2, 3],
  [0, 1],
  [0, 1],
  [2, 3],
  [2, 3],
  [4, 5],
  [4, 5],
  [0, 1],
  [0, 1],
  [0, 1, 5],
  [0, 1, 7],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 5],
  [0, 1, 7],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 5],
  [0, 1, 7],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 5],
  [0, 1, 7],
  [0, 4, 7],
  [0, 4, 5],
  [1, 5, 6],
  [1, 4, 5],
  [0, 5, 6],
  [0, 4, 5],
  [1, 4, 7],
  [1, 4, 5],
  [0, 1, 5],
  [0, 1, 7],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 4],
  [0, 1, 6],
  [0, 1, 5],
  [0, 1, 7],
  [0, 4, 7],
  [0, 4, 5],
  [1, 5, 6],
  [1, 4, 5],
  [0, 5, 6],
  [0, 4, 5],
  [1, 4, 7],
  [1, 4, 5],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1, 2, 3],
  [0, 1, 2, 3],
  [0, 4, 5],
  [0, 4, 7],
  [0, 4, 5],
  [0, 5, 6],
  [1, 4, 5],
  [1, 5, 6],
  [1, 4, 5],
  [1, 4, 7],
  [4, 5, 6, 7],
  [4, 5, 6, 7],
  [4, 5, 6, 7],
  [4, 5, 6, 7]]

def coordinates (c : Fin 76) : List (Fin 8) := table[c.val]!

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem coordinates_independent (c : Fin 76) :
    IndependentCornerMax.IndependentOn (FastFiniteTables.fastCuts c)
      (coordinates c).toFinset := by
  fin_cases c <;> unfold IndependentCornerMax.IndependentOn <;> decide

#print axioms coordinates_independent

end PeaceableQueens.UpperBound.IndependentCutMasks
